Creando primera guia
cosola-macile/guias pull request #1
Opened 2017-06-12 16:37 UTC by Mariaa122

### Issues

¿Qué se está resolviendo?
Creando una nueva guia

### Todos

¿Qué queda por hacer?
Revisar y terminar

### Áreas impactadas

¿Qué páginas o componentes están afectados?
nueva-guia.md

2017-06-13 00:22 UTC, misscs requested changes
👍 Buen comienzo pero puede ser aún mejor. Cuando estas escribiendo documentación es importante pensar en al usuario más básico. Imagines una persona completamente nueva a estas temas.

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +#Preparando Máquinas
El nombre del archivo debe corresponder con el título de la guia. 

No se olvide de utilizar un espacio después del `#`

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +	...
Parece que te  olvido copiar el texto que deben entrar aquí

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +	```
Que deber ver si se instala correctamente?

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +	Descargar nodejs
Donde voy a descargar nodejs?

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +	Descargar nodejs
Que versión de nodejs debo instalar?

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +	Abrir y cerrar el powerShell
Cuando abro y cerro el powershell?

Cómo podemos cambiar powershell en el futuro para outra línea de comando, que piensas si usamos el termino "línea de comando"?

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +	npm install http-server -g
Este paso no está relacionada con la preparación de nuestras computadoras. Es más bien algo que podemos instalar si queremos crear un servidor local. Yo pienso que podemos crear outra guia sobre trabajando localement. Que piensas?

2017-06-13 00:22 UTC, misscs commented on nueva-guia.md
> +
Hmm, parece como no quieras escribir más. Los otros pasos después de # 1 no están correctamente formateados.

2017-06-13 00:24 UTC, misscs commented
@Mariaa122 Yo terminé con mis revisiones. Avísame si algo no está claro. 

@YaArias Puedes también puedes revisar?

2017-06-13 14:32 UTC, misscs approved these changes

2017-06-13 14:34 UTC, misscs commented
Yo lo encuentro 👍. @YaArias que piensas? Todo esta claro? Si tuvieras que usar estas instrucciones, puedes seguirlas?

2017-06-13 14:41 UTC, merged

2017-06-13 14:44 UTC, YaArias commented
Me parece una guia muy precisa y que va al punto en pocas palabras. De seguro que seguiria las instrucciones de inmediato. :-) 👍

2017-09-04 13:50 UTC, cosola commented on preparando-maquinas.md
> +Esta preparación es para las máquinas de windows.
El url correcto es: https://chocolatey.org/